"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_sampling_c3_debug(object):
    __slots__ = ["utime", "is_c3_mode", "is_teleop", "is_force_tracking", "is_forced_into_c3", "in_pose_tracking_mode", "mode_switch_reason", "source_of_pursued_target", "detected_goal_changes", "best_progress_steps_ago", "lowest_cost", "lowest_pos_and_rot_current_cost", "lowest_position_error", "lowest_orientation_error", "current_pos_error", "current_rot_error"]

    __typenames__ = ["int64_t", "boolean", "boolean", "boolean", "boolean", "boolean", "int32_t", "int32_t", "int32_t", "int32_t", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.is_c3_mode = False
        self.is_teleop = False
        self.is_force_tracking = False
        self.is_forced_into_c3 = False
        self.in_pose_tracking_mode = False
        self.mode_switch_reason = 0
        self.source_of_pursued_target = 0
        self.detected_goal_changes = 0
        self.best_progress_steps_ago = 0
        self.lowest_cost = 0.0
        self.lowest_pos_and_rot_current_cost = 0.0
        self.lowest_position_error = 0.0
        self.lowest_orientation_error = 0.0
        self.current_pos_error = 0.0
        self.current_rot_error = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_sampling_c3_debug._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbbbbbiiiiffffff", self.utime, self.is_c3_mode, self.is_teleop, self.is_force_tracking, self.is_forced_into_c3, self.in_pose_tracking_mode, self.mode_switch_reason, self.source_of_pursued_target, self.detected_goal_changes, self.best_progress_steps_ago, self.lowest_cost, self.lowest_pos_and_rot_current_cost, self.lowest_position_error, self.lowest_orientation_error, self.current_pos_error, self.current_rot_error))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_sampling_c3_debug._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_sampling_c3_debug._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_sampling_c3_debug()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.is_c3_mode = bool(struct.unpack('b', buf.read(1))[0])
        self.is_teleop = bool(struct.unpack('b', buf.read(1))[0])
        self.is_force_tracking = bool(struct.unpack('b', buf.read(1))[0])
        self.is_forced_into_c3 = bool(struct.unpack('b', buf.read(1))[0])
        self.in_pose_tracking_mode = bool(struct.unpack('b', buf.read(1))[0])
        self.mode_switch_reason, self.source_of_pursued_target, self.detected_goal_changes, self.best_progress_steps_ago, self.lowest_cost, self.lowest_pos_and_rot_current_cost, self.lowest_position_error, self.lowest_orientation_error, self.current_pos_error, self.current_rot_error = struct.unpack(">iiiiffffff", buf.read(40))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcmt_sampling_c3_debug in parents: return 0
        tmphash = (0xf1ea648aec7142de) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_sampling_c3_debug._packed_fingerprint is None:
            lcmt_sampling_c3_debug._packed_fingerprint = struct.pack(">Q", lcmt_sampling_c3_debug._get_hash_recursive([]))
        return lcmt_sampling_c3_debug._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_sampling_c3_debug._get_packed_fingerprint())[0]

