"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcmt_list_of_strings(object):

    __slots__ = ["utime", "num_strings", "strings"]

    __typenames__ = ["int64_t", "int32_t", "string"]

    __dimensions__ = [None, None, ["num_strings"]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.num_strings = 0
        """ LCM Type: int32_t """
        self.strings = []
        """ LCM Type: string[num_strings] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_list_of_strings._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.num_strings))
        for i0 in range(self.num_strings):
            __strings_encoded = self.strings[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__strings_encoded)+1))
            buf.write(__strings_encoded)
            buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_list_of_strings._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_list_of_strings._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_list_of_strings()
        self.utime, self.num_strings = struct.unpack(">qi", buf.read(12))
        self.strings = []
        for i0 in range(self.num_strings):
            __strings_len = struct.unpack('>I', buf.read(4))[0]
            self.strings.append(buf.read(__strings_len)[:-1].decode('utf-8', 'replace'))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_list_of_strings in parents: return 0
        tmphash = (0xae606f72db379b6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_list_of_strings._packed_fingerprint is None:
            lcmt_list_of_strings._packed_fingerprint = struct.pack(">Q", lcmt_list_of_strings._get_hash_recursive([]))
        return lcmt_list_of_strings._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_list_of_strings._get_packed_fingerprint())[0]

